name: bethlehem
description: A router for RawDart SPA Development and AngularDart Development.
version: 1.0.1-dev.1
homepage: https://github.com/arxarinze/bethlehem

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  angular: ^6.0.0-alpha
  angular_components: ^1.0.2
  collection: ^1.14.13
#  path: ^1.7.0


dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  build_runner: '>=1.6.2 <2.0.0'
  build_web_compilers: '>=2.12.0 <3.0.0'
  angular_test: ^2.3.1
  build_test: ^0.10.8
